/* global styles for msg box */
/*MSG_HEADER_FONT = "'Press Start 2P', sans-serif";*/
MSG_CONTENT_FONT = "'Press Start 2P'";/*"VT323, sans-serif";*/

MSG_SUCCESS_COLOUR = "#008000";
MSG_INFO_COLOUR = "#2196F3";
MSG_WARNING_COLOUR = "#693A25";
MSG_ERROR_COLOUR = "#FD0000";
MSG_CONFIRM_COLOUR = "#D4BA7C";
MSG_INPUT_COLOUR = "#D4BA7C";

MSG_TEXT_CONFIRM_OK = "Yes";
MSG_TEXT_CONFIRM_CANCEL = "No";
MSG_TEXT_CONFIRM = "Question?";
